### ISSUE TITLE
Implement keyboard shortcuts

### ISSUE THREAD

**Issue by martincarles** [leorolland/NoxuNote#24]
C'est une app sympa et potentiellement très utile mais cela manque de raccourcis clavier.
Le but affiche étant de faciliter une prise de notes facile et rapide, l'utilisation de la souris doit être minimisée autant que possible.

Lorsque les boutons "Supprimer" et "Modifier" apparaissent, il est très tentant de vouloir appuyer sur "Suppr" pour Supprimer, "Echap" pour en sortir.
Je ne suis pas certain que le bouton "Modifier" soit utile tout court puisqu'il suffit d'appuyer sur "Entrée" pour faire un retour a la ligne et continuer a écrire.

Je suggère également de rajouter des raccourcis pour accéder a l'outil dessin, insertion d'image etc.

**Comment by leorolland** [comment]
Merci beaucoup pour ton retour c'est vraiment encourageant de voir que de plus en plus de personnes s'intéressent à NoxuNote. Je pense faire évoluer l'application vers une édition de texte avec quilljs c'est à dire avec un moteur Wysiwyg de traitement de texte pour ensuite rajouter la surcouche de NoxuNote (raccourcis etc) car je n'aime pas le système de blocs à modifier/supprimer. C'est pas naturel et on me l'a déjà fait remarquer. Dans un premier temps je pense que ce sera ma priorité de développement (avec un passage sous angular possible) ensuite je pofinerai avec des raccourcis clavier. En revanche tu peux faire une PR sur la version actuelle si la fonctionnalité te tiens à cœur en attendant les futures versions avec quill.js
Merci encore,
Leo

**Comment by martincarles** [comment]
Salut Leo, merci pour ton retour. Effectivement, le système de blocs est surprenant au premier abord.
Je n'ai malheureusement pas les connaissances nécessaires pour soumettre une PR la dessus.
Mais j'attendrais avec impatience la Version 2!

**Comment by leorolland** [comment]
Je viens de merge la derniere version avec l'éditeur summernote (qui règle tous les soucis évoqués) ! Merci pour ton aide ! N'hésite pas à pull la derniere version de master pour tester 👍
