### ISSUE TITLE
Retour à la ligne si prefix ">"

### ISSUE THREAD

**Issue by victordrnd** [leorolland/NoxuNote#9]
Permettre le retour à la ligne quand on saisie du code via le prefix ">" serait vraiment pratique pour la mise en page du code appuyer sur "esc" permet de sortir du bloc à la limite

**Comment by leorolland** [comment]
Oui c'est effectivement indispensable pour écrire du code. Mais je réfléchis à utiliser quill.js comme éditeur de base texte des notes. L'éditeur "NoxuNote" n'est pas top quand il s'agit de sélectionner, copier coller etc ... Je pense donc essayer d'adapter NoxuNote à une librairie WYSIWYG qui ressemble à un traitement de texte, cela sera plus naturel pour les utilisateurs, sélection, retours naturels à la ligne (plus de fonctionnement par blocs). Qu'en penses-tu ?

**Comment by cod3x69** [comment]
Oui mais il faut absolument gardé le fonctionnement actuel semblable au
language markdown

**Comment by leorolland** [comment]
Je suis d'accord avec toi 👍

**Comment by leorolland** [comment]
A voir comment intégrer le code (syntax highlighting) dans la dernière version, avec summernote, qui ne le gère pas encore ! Si j'y travaille je songerais à suivre tes conseils 👍 

D'ailleurs j'ai un peu réduit le nombre de raccourcis markdown pour l'instant on n'a que les ## mais c'est temporaire je te rassure !
